### ISSUE TITLE
Indentation goes crazy with keywords in docstrings

### ISSUE THREAD

**Issue by baggepinnen** [JuliaEditorSupport/atom-language-julia#111]
The following docstrings all cause faulty indentation on version 0.12.0. Both issues can be resolved by changing the letter f/t in function/type to capital F/T.

Furthermore, the auto indentation always removes the 4 spaces in front of the first row in the docstring. 

```julia
"""
    myfun()

This function does something
"""
function myfun()
    println("Hello")
end


"""
    MyType

This type does something
"""
struct MyTpy
    x
end
```
After auto indentation, the above code looks like
```julia

"""
myfun()

This function does something
    """
    function myfun()
        println("Hello")
    end
    
    
    """
    MyType
    
    This type does something
        """
        struct MyTpy
            x
        end
```

**Comment by pfitzseb** [comment]
I'd argue that this is an Atom bug -- the `Auto Indent` command shouldn't look at string contents, just like the normal auto indentation doesn't.
