### ISSUE TITLE
"in" no longer highlighted in for loop

### ISSUE THREAD

**Issue by kescobo** [JuliaEditorSupport/atom-language-julia#113]
In both loops and comprehensions, the `in` in a for loop used to be highlighted in the same color, as `for`, `end`, `if` and so on. I've noticed lately this is no longer the case.

![screenshot 2017-08-21 12 42 03](https://user-images.githubusercontent.com/3502975/29529605-587bcef2-866e-11e7-93be-a672b0caa097.png)

Any reason for the change? (if it's a problem in a different package, sorry about the spurious issue)

**Comment by pfitzseb** [comment]
Yeah, I've changed the tokenization of `in` to `operator` instead of `keyword` highlighting in https://github.com/JuliaEditorSupport/atom-language-julia/pull/108. Some themes have operators highlighted in a different colour, but most don't.

**Comment by kescobo** [comment]
That makes sense. I found the color my theme uses for keywords, but I'm not entirely sure what to add to my `styles.less` file to get the operator to be colored. Can you point me in the right direction?

**Comment by pfitzseb** [comment]
```
@import "syntax-variables";
.syntax--julia .syntax--operator {
  color: @syntax-color-tag;
}
```
should work. Most themes define [these](https://github.com/atom/atom/blob/master/static/variables/syntax-variables.less) colours, so you should be able to keep your `styles.less` generic enough to keep the code good looking even if you change your theme :)

**Comment by kescobo** [comment]
Cool, that worked, though it ends up being a different color than the keywords in my current theme. I guess are also operators `=`, `:` etc, so changing the color of in changes all of those too, and will take some getting used to, but probably for the best. Thanks for the help!
