### ISSUE TITLE
syntax highlight problem

### ISSUE THREAD

**Issue by marius311** [JuliaEditorSupport/atom-language-julia#123]
After a newline and `_)`, the `"""` doesn't appear to be parsed as closing the string. 

![image](https://user-images.githubusercontent.com/1510968/32473109-1f95150a-c366-11e7-8c29-7940cf970311.png)

I'm on `atom-language-julia 0.13`

**Comment by pfitzseb** [comment]
Dup of https://github.com/JuliaEditorSupport/atom-language-julia/issues/33.

**Comment by marius311** [comment]
Per https://github.com/atom/language-gfm/issues/44#issuecomment-274046078 I switched to `language-markdown` which fixes it. Well, really it just gets rid of syntax highlighting within Julia `""" ... """`  strings entirely. However, in its own Markdown file, its clear `language-markdown` correctly highlights my code snippet above, whereas `language-gfm` does not. 

Not sure if I'm understanding how these all work together right, but is there any way to make Julia use `language-markdown` for highlighting docstrings when I have `language-gfm` turned off?

**Comment by pfitzseb** [comment]
Yeah:
![image](https://user-images.githubusercontent.com/6735977/32492059-3e4a1254-c3b9-11e7-9251-f9b45c74f8c1.png)
