### ISSUE TITLE
0.13.0. Another highlightning issue.

### ISSUE THREAD

**Issue by xanfus** [JuliaEditorSupport/atom-language-julia#132]
Everything beyond the last semicolon goes with same color as strings do. 
```
plt.plot(mean(lionposup[:,1201:2400],2),1:2:1399,"-",color="tomato");plt.plot(mean(lionposdown[:,1201:2400],2),1:2:1399,"--",color="tomato");plt.plot(mean(lionnegup[:,1201:2400],2),1:2:1399,"-",color="mediumslateblue");plt.plot(mean(lionnegdown[:,1201:2400],2),1:2:1399,"--",color="mediumslateblue")
```

**Comment by pfitzseb** [comment]
This seems to be an Atom "issue" -- as soon as a line is longer than N chars syntax highlighting is turned off. And if the N-th char is inside a string the remainder of that line will be coloured as a string as well.

Consider using linebreaks :)
