### ISSUE TITLE
wrongly syntax highlighting

### ISSUE THREAD

**Issue by iblis17** [JuliaEditorSupport/atom-language-julia#134]
Original issue here: https://github.com/github/linguist/issues/3950

And here is the file `MXNet/src/ndarray.jl`
![screenshot from 2017-12-14 17-27-39](https://user-images.githubusercontent.com/761623/33985016-49fe10ac-e0f4-11e7-920f-987994b3d291.png)

**Comment by pfitzseb** [comment]
This is fixed on master. I'll publish a new release asap.

**Comment by iblis17** [comment]
thanks 👍

**Comment by pfitzseb** [comment]
Alright, 0.14 is out. GitHub syntax highlighting should be updated some time soon, iiuc.
