### ISSUE TITLE
< in docstring breaks highlighting

### ISSUE THREAD

**Issue by pfitzseb** [JuliaEditorSupport/atom-language-julia#135]
```
"""
    Rational{T<:Integer} <: Real

Rational number type, with numerator and denominator of type `T`.
"""
struct Rational{T<:Integer} <: Real
```

See https://github.com/burodepeper/language-markdown/issues/183.

Workaround is to disable `language-html`, but that is won't work for github highlighting anyways I think. Furthermore, `language-markdown` doesn't support indented codeblocks at all (see https://github.com/burodepeper/language-markdown/issues/178), so I'm not sure if there's any value keeping markdown syntax highlighting around at all. Opinions, @sglyon, @MikeInnes, @davidanthoff (not sure if that's important for VSCode anyways)?

**Comment by davidanthoff** [comment]
I think it would be fine to not do markdown highlighting within julia strings (that is essentially what this is about, right?)

**Comment by pfitzseb** [comment]
This specifically is about docstrings (or rather un-indented triple quoted strings right before a non-empty line or something like that). 
The two Atom markdown syntax highlighters aren't compatible with Julia syntax (language-gfm leaks out of the docstring pretty often and language-markdown kind of does too *and* doesn't support indented code blocks), but I don't know about VSCode's markdown syntax.

**Comment by sglyon** [comment]
I’m in favor of removing markdown altogether. It seems to cause more issues than it is worth

**Comment by davidanthoff** [comment]
Ah, ok. I think I'm still in favor of just removing any formatting within julia strings, that seems ok.
