### ISSUE TITLE
Suggest "end" while typing "end"

### ISSUE THREAD

**Issue by davidavdav** [JuliaEditorSupport/atom-language-julia#137]
I don't know if autocompletion is part of atom-language-julia or not. 

But this drives me nuts: every time I type "\<return> end \<tab>", by which I mean "insert the keyword "end" and unindent (which is what the \<tab> is supposed to do), atom changes "end" into "encode" because it thinks that that is what I mean. 

Could "end" be inserted in the list of Julia-language keywords?

**Comment by pfitzseb** [comment]
Autocompletions aren't really handled by this package -- I'd recommend either using Juno or possibly https://github.com/pfitzseb/atom-julia-lsp-client (not sure if that still works, tbh) to handle those.

**Comment by davidavdav** [comment]
Sorry about that, understanding the taxonomy of the various packages is not always that easy for me.

**Comment by pfitzseb** [comment]
No worries :) It's fine to open issues basically wherever (preferably Juno.jl IIRC) -- someone will know where to best put them.

**Comment by pfitzseb** [comment]
Oh btw, if you *are* using Juno then you should definitely have completions for `end` (and the other keywords); if not, then that's a bug.
