### ISSUE TITLE
Console won start: ERROR: unknown option `-3`

### ISSUE THREAD

**Issue by pedrohnv** [JuliaEditorSupport/atom-language-julia#141]
Whenever I open a console (in Atom) and try to start Julia, I get the "ERROR: unknown option `-3`" and a "Julia has stopped: 1" message. I can run Julia from a terminal outside Atom.

My OS is Xubuntu 16.04, 64-bit. I had a previously failed Julia install. I also installed Juno-related packages in Atom.

**Comment by pfitzseb** [comment]
You're probably running an old version of Julia -- Juno only supports 0.6.

**Comment by pedrohnv** [comment]
Indeed I had julia 0.4, which I got with apt-get. Didn't pay attention to that. I then downloaded the latest binary (0.6.2) and everything is working as expected.

Sorry I couldn't answer earlier.
