### ISSUE TITLE
Error with brackets due to function_decl, function_call, array...

### ISSUE THREAD

**Issue by apieum** [JuliaEditorSupport/atom-language-julia#142]
**Parens are not correctly highlighted, I've removed function_decl and function_call then it worked.**
It's Test.jl from stdlib on latest julia so you can test yourself. 

![code_function_decl](https://user-images.githubusercontent.com/723728/37475104-3611f192-2872-11e8-9de0-712a6e31c211.png)
![details_bug](https://user-images.githubusercontent.com/723728/37475105-36440844-2872-11e8-8a9f-f117814605c3.png)

**Similar problem with array:**
![image](https://user-images.githubusercontent.com/723728/37475343-c719ee42-2872-11e8-8ef1-1ef41f41b9f3.png)
![image](https://user-images.githubusercontent.com/723728/37475372-dabfc368-2872-11e8-9b6c-c9fa15bcb751.png)

**Comment by apieum** [comment]
Sorry I've no idea how to fix it, I've never writen an atom language syntax. I'll have a look at documentation to see if I can help.

**Comment by apieum** [comment]
I think it's done. 
Would you please check it, and tell me if you want a PR with a single commit or with 3. (solution was either to capture parens and add meta.bracket.julia, or to put parens inside a look ahead). Thx

**Comment by pfitzseb** [comment]
Just open a PR, we can discuss the rest there :) Thanks for fixing this!

**Comment by apieum** [comment]
oups, I've not seen spec, I've to make them pass first.
