### ISSUE TITLE
language-julia CSON file duplicate Key

### ISSUE THREAD

**Issue by Admiralhunter** [JuliaEditorSupport/atom-language-julia#144]
Hello everyone im new to atom and wanted to try using it to program Julia. I followed the instructions from junolab.org and I kept getting errors from the package "Language-julia". The error kept stating the snippet Language-julia.cson had a duplicate key. After fumbling around I opened the CSON to see what was throwing this error and noticed at the very top this was in the file.

`".source.julia":
  "Docstring":
    prefix: "doc"
    body: '''
      @doc doc"""
      $1($2)
      $3
      """ ->
    '''
".source.julia":
  "Documented function":
    prefix: "fxd"
    body: '''
      @doc doc"""
      $1($2)
      $3
      """ ->
      function $1($2)
      	$4
      end
    '''`

As you can see the key ".source.julia." appears twice but it seems its doing something differently in each of them. I discovered if i renamed the second key to ".source.julia2" my error disappeared (for now...) but i assume this is not a good approach for fixing this problem. I'm wondering if I screwed up the installation somewhere or how to best fix this.

**Comment by lnacquaroli** [comment]
Same thing happened to me after updating atom to v1.25 and reinstalling language-julia. Looks like it work anyway, but it is strange nonetheless.

**Comment by pfitzseb** [comment]
Fixed on master. New version will be out soon.
