### ISSUE TITLE
Atom on mac - Failed to load snippets from ...

### ISSUE THREAD

**Issue by jazbu** [JuliaEditorSupport/atom-language-julia#146]
Hello, I'm new to Julia and atom. I installed both of them. When opening Atom the following error messages appear:

```
Failed to load snippets from '/Users/mymac/.atom/packages/language-julia/snippets/language-julia.cson'
```
```
/Users/mymac/.atom/packages/language-julia/snippets/language-julia.cson: Duplicate key '.source.julia'
```
<img width="1038" alt="screen shot 2018-03-22 at 14 37 52" src="https://user-images.githubusercontent.com/27978044/37773787-c9308300-2dde-11e8-9830-1a292d651109.png">

What should I do?

**Comment by JonnyCBB** [comment]
I had the same problem. I've just put in a [pull request](https://github.com/JuliaEditorSupport/atom-language-julia/pull/147) that should fix it.

**Comment by jazbu** [comment]
Many Thanks @JonnyCBB. Now it works!

I also installed the following packages (I don't know if it had an effect): 
- uber-juno 0.1.2
- julia-client 0.6.10
- Hydrogen 2.3.0
- Julia-client 0.6.10

**Comment by Mushu62** [comment]
@bjce  Have you been able to solve this issue? I have the same problem when loading snippets in Atom ...

**Comment by bjce** [comment]
@Mushu62 : after the pull request of JonnyCBB it worked for me as stated in the comment on Mar 27. I could not explain why though
