### ISSUE TITLE
Some colors missing for Base16 Tomorrow Dark theme?

### ISSUE THREAD

**Issue by x-ji** [JuliaEditorSupport/atom-language-julia#149]
Not sure if this is an issue with this package but I'm going to post here for now. Base16 Tomorrow Dark is one of the themes that come with Atom by default, and it is also the theme that I normally use across all editors. However, for some reason the syntax highlighting of Julia files seems to be amiss under this theme. For example, in `v::UInt32`, the `UInt32` part has the same color as `v`. This doesn't happen with the other three default themes.

**Comment by pfitzseb** [comment]
Hm, I'd say this is an "issue" with the syntax theme -- the author just decided to not highlight types any differently than e.g. variables, which is a valid choice. You'll either need to modify the theme yourself or use a different theme altogether.

As a simple tweak, try pasting the following into your user stylesheet (open the command palette and type in `Application: Open Your Stylesheet`):
```
.theme-base16-tomorrow-dark-theme {
  atom-text-editor {
    .syntax--support {
      color: #81a2be;
    }
  }
}
```
