### ISSUE TITLE
Autoindent the first line in docstrings

### ISSUE THREAD

**Issue by stakaz** [JuliaEditorSupport/atom-language-julia#152]
Hello, when using auto indentation in a file the first lien in the docstring gets aligned most left without spaces.

```julia
"""
    f(x) = ...

Function to ...
"""
```

becomes 

```julia
"""
f(x) = ...

Function to ...
"""
```

which is bad since the function name will not be interpreted as julia code in the last case.

Is there a possibility to set up the julia grammar to circumvent this and do not indent in docstrings?

**Comment by pfitzseb** [comment]
Basically the same as https://github.com/JuliaEditorSupport/atom-language-julia/issues/111 -- it doesn't really make sense to apply auto indentation to strings at all.
