### ISSUE TITLE
Highlighting multiline string macros doesn't work

### ISSUE THREAD

**Issue by rapus95** [JuliaEditorSupport/atom-language-julia#153]
Hey, couldn't test it for juno, but since it is a bug for VS Code I guess you have the same problem (since VS Code copies the highlighting code from here)
According issue over there: https://github.com/JuliaEditorSupport/julia-vscode/issues/530

**Comment by pfitzseb** [comment]
Would you expect something different from the following?
![image](https://user-images.githubusercontent.com/6735977/43215145-abe924ae-903b-11e8-8b75-a19813189970.png)
