### ISSUE TITLE
Remove new from keywords?

### ISSUE THREAD

**Issue by Roger-luo** [JuliaEditorSupport/atom-language-julia#165]
https://github.com/JuliaEditorSupport/atom-language-julia/blob/532b6f201ae30528165212917b32835d60c916bd/grammars/julia.cson#L183

Ref: https://github.com/JuliaEditorSupport/julia-vscode/issues/498#issuecomment-428200399

**Comment by pfitzseb** [comment]
Yeah, makes sense to me.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JuliaEditorSupport/atom-language-julia/commit/f6c20fceff7305b4c6c2c88a01ce93bf317c68bc.
