### ISSUE TITLE
Feature request: Syntax highlighting with isa 

### ISSUE THREAD

**Issue by Datseris** [JuliaEditorSupport/atom-language-julia#166]
![image](https://user-images.githubusercontent.com/19669089/47094294-3c2fea80-d22b-11e8-8354-e592e7b6cee0.png)

Is it possible for the second case to also apply to the first?

Crossref: https://github.com/JunoLab/Juno.jl/issues/177#issuecomment-430685682

**Comment by pfitzseb** [comment]
Theme issue. We're already tokenizing this as an operator.
