### ISSUE TITLE
Different highlighting of function name depending on the number of args to `where`

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/atom-language-julia#168]
<img width="705" alt="screenshot 2018-11-03 at 12 13 06" src="https://user-images.githubusercontent.com/1282691/47954580-df8a3a80-df61-11e8-8bf8-cacb00f33887.png">

I feel the `convert` should highlight the same here.

**Comment by pfitzseb** [comment]
Dup of https://github.com/JuliaEditorSupport/atom-language-julia/issues/158.
