### ISSUE TITLE
Foreign language syntax highlighting

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaEditorSupport/atom-language-julia#175]
There are several foreign language string macros in the julia ecosystem. I know of
```julia
py""
R""
cxx""
js""
```
Would be nice, if you have they had the corresponding Syntax highlighting

**Comment by pfitzseb** [comment]
We have all of those now, I think.

**Comment by BeastyBlacksmith** [comment]
do you mean via https://github.com/JuliaEditorSupport/atom-language-julia/pull/187 ?

**Comment by pfitzseb** [comment]
No, via https://github.com/JuliaEditorSupport/atom-language-julia/pull/177 and https://github.com/JuliaEditorSupport/atom-language-julia/pull/183.

**Comment by BeastyBlacksmith** [comment]
Nice, I notice that incomplete expressions affect highlighting beyond the closing `"""`

![Screenshot_2019-05-22_11-57-52](https://user-images.githubusercontent.com/18145188/58166601-78786d00-7c8a-11e9-888f-7627dcb40c79.png)

**Comment by pfitzseb** [comment]
Yeah, that's a fundamental problem with Atom's syntax highlighting. I'd suggest using valid syntax :D

**Comment by BeastyBlacksmith** [comment]
It's like a very pushy linter ^^

**Comment by BeastyBlacksmith** [comment]
https://github.com/JuliaInterop/MathLink.jl is being revived, so Mathematica syntax is coming your way via `W""` and
```julia
W``
```
