### ISSUE TITLE
Highlighting of "end"

### ISSUE THREAD

**Issue by dpo** [JuliaEditorSupport/atom-language-julia#176]
I use the Atom Light syntax theme, and for some reason, the keyword `end` is highlighted bizarrely:
<img width="185" alt="Screen Shot 2019-03-13 at 14 26 12" src="https://user-images.githubusercontent.com/38760/54304803-52ed2a00-459c-11e9-8ad1-5cd475555b0d.png">
I would expect it to be bold and black, just like `function`, `for`, etc. Or is it intentional?

Thanks.

**Comment by pfitzseb** [comment]
You can just put
```
atom-text-editor.editor {
  .syntax--keyword.syntax--end {
    opacity: 1;
  }
}
```
into your User Stylesheet.

Note that it isn't actually this package that lowers the opacity, it's [julia-client](https://github.com/JunoLab/atom-julia-client/blob/master/styles/julia-client.less#L41).
