### ISSUE TITLE
Highlighting for single-quoted string in triple-quoted regexp is broken.

### ISSUE THREAD

**Issue by twadleigh** [JuliaEditorSupport/atom-language-julia#192]
An example of this can be found at https://github.com/twadleigh/julia-syntax-test-cases/blob/master/corner_cases.jl. The breakage is visable from line 92 on, where everything looks like a string.

The failure is visible with github syntax highlighting and also propagates downstream to `julia-vscode`, which depends on a transformation of this repository's `julia.cson`.

**Comment by pfitzseb** [comment]
Good find! 
That's a nice test file, we should think about adding some of the corner cases to our specs.
