### ISSUE TITLE
Wrong syntax highlighting when `::` is followed by a macro interpolation

### ISSUE THREAD

**Issue by singularitti** [JuliaEditorSupport/atom-language-julia#208]
I find that when `::` is followed by a macro interpolation like `$var`, it shows the wrong syntax highlighting. A potential bug? Is it fixable? This is found in VSCode, but they simplify copy `Juno`'s tokenize file, so I suppose the same bug happens in Atom, too.
![image](https://user-images.githubusercontent.com/25192197/73513533-dd5c9900-43bb-11ea-95fa-ea92ffb87e18.png)
Test code: https://github.com/FugroRoames/Rotations.jl/blob/031a678ae2e7fc578d436706be657d053ed78018/src/euler_types.jl#L12-L34

**Comment by pfitzseb** [comment]
Btw, it's usually enough to point to the github repo with the code that's erroneously highlighted -- they use this repo as well ;)
