### ISSUE TITLE
PyCall Highlighting

### ISSUE THREAD

**Issue by cojua8** [JuliaEditorSupport/atom-language-julia#211]
Hi,

When using PyCall with the

py"""
some python code
""" 
syntax, the editor does not read it as a code block, so all the julia code after it is colored as if it was a comment

**Comment by pfitzseb** [comment]
I *think* this happens when your python code is invalid (e.g. not indented correctly or whatnot). Can you make sure that's not the case?

**Comment by cojua8** [comment]
Forgot to say I am working on VSCode. In Juno it works fine.

**Comment by marius311** [comment]
The original code is fine for me now, but any chance this could be fixed as well?

![image](https://user-images.githubusercontent.com/1510968/87503856-1ad77a80-c61a-11ea-806e-1e6590be9e78.png)

Indenting or removing the trailing newline fixes it: 

![image](https://user-images.githubusercontent.com/1510968/87503883-2c208700-c61a-11ea-81be-59d10c23944f.png)

![image](https://user-images.githubusercontent.com/1510968/87503899-32aefe80-c61a-11ea-9f06-d25780fe359b.png)

**Comment by pfitzseb** [comment]
No, I don't think so.

**Comment by marius311** [comment]
Surely there must be _some_ way, right? :) If its a matter of staring at regex'es for long enough, I might be motivated enough to do it, if you could point me in the right direction?
