### ISSUE TITLE
[BUG] Formatted strings which end in "u" break highlighting

### ISSUE THREAD

**Issue by marius311** [JuliaEditorSupport/atom-language-julia#213]
Repasting the original contents of https://github.com/JunoLab/Juno.jl/issues/528 over here: 

## Details
- Atom version: 1.45.0
- Julia version: 1.3.1
- OS: Linux
- Package versions:
  - Atom.jl: v0.12.9
  - julia-client: 0.12.3
  - ink: 0.12.3

## Steps to reproduce

Looks like a formatted string (in my example with `py`) which ends in `u` breaks highlighting. E.g.: 

```julia
py"u"
let # <- broken here
end
```

```julia
py"x"
let # <- ok
end
```

**Comment by pfitzseb** [comment]
Turns out that this is being tokenized as Python's `u"`, which steals the `"` from us. Not sure what we can realistically do about that except removing all `xx"stuff"` highlighting -- the `"""` forms should be mostly fine.

**Comment by marius311** [comment]
If those are the choices I'd much prefer keeping the `xx"stuff"` and living with this edge case.
