### ISSUE TITLE
Transpose operator (') breaks syntax highlighting on GitHub

### ISSUE THREAD

**Issue by charleskawczynski** [JuliaEditorSupport/atom-language-julia#218]
It seems that the transpose operator (') breaks syntax highlighting on GitHub. Here's an example screenshot:

<img width="600" alt="Screen Shot 2020-07-07 at 8 27 40 AM" src="https://user-images.githubusercontent.com/1880641/86805341-a6567780-c02c-11ea-8a45-62e14e3e3018.png">

Funny enough, things remain broken until another transpose occurs. Then, the syntax highlighting kicks back in:

<img width="461" alt="Screen Shot 2020-07-07 at 8 35 31 AM" src="https://user-images.githubusercontent.com/1880641/86805598-dbfb6080-c02c-11ea-9eea-e7299888566b.png">

**Comment by pfitzseb** [comment]
It's not transposes per se, it's the specific `k̂'` sequence -- we're not correctly detecting `k̂` as a valid identifier. The correct regex for that is `(?:[[:alpha:]_\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}⅀-⅄∿⊾⊿⊤⊥∂∅-∇∎∏∐∑∞∟∫-∳⋀-⋃◸-◿♯⟘⟙⟀⟁⦰-⦴⨀-⨆⨉-⨖⨛⨜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃ⁱ-⁾₁-₎∠-∢⦛-⦯℘℮゛-゜𝟎-𝟡]|[^\p{^So}←-⇿])(?:[[:word:]_!\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}⅀-⅄∿⊾⊿⊤⊥∂∅-∇∎∏∐∑∞∟∫-∳⋀-⋃◸-◿♯⟘⟙⟀⟁⦰-⦴⨀-⨆⨉-⨖⨛⨜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃ⁱ-⁾₁-₎∠-∢⦛-⦯℘℮゛-゜𝟎-𝟡\p{Mn}\p{Mc}\p{Nd}\p{Pc}\p{Sk}\p{Me}\p{No}′-‷⁗]|[^\p{^So}←-⇿])*` ([ref](https://gist.github.com/pfitzseb/1e5cb6c52b196bb556983959c1aef02b)), but for some reason that wasn't working the last time I tried it here.

Will give it another go though.

**Comment by charleskawczynski** [comment]
Oh, wow! Thanks for looking into this!

**Comment by klamike** [comment]
Seems this is happening again

<img width="369" height="219" alt="Image" src="https://github.com/user-attachments/assets/b1c74751-c859-4368-b993-bf1e8926d811" />

(screenshot from GitHub, shows that text between transposes gets highlighted as a string)
