### ISSUE TITLE
Tokenize TODO in comments

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaEditorSupport/atom-language-julia#232]
The Python grammar does this:

![image](https://user-images.githubusercontent.com/8310743/100527785-6474cc00-319b-11eb-9fe7-f0cf6f0e5643.png)

**Comment by pfitzseb** [comment]
We can do that, but I feel like using a separate extension for this makes more sense (those exist for VSCode and Atom both).

**Comment by CameronBieganek** [comment]
Hmm, I see [this one](https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments), but that's a bit more colorful than I would like my comments to be. I think having basic `TODO` highlighting would be a useful feature. :)

**Comment by CameronBieganek** [comment]
Bump. This would be nice to have. The Python extension tokenizes both `TODO` and `NOTE` in comments.
