### ISSUE TITLE
Make more specific token for `::`

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaEditorSupport/atom-language-julia#238]
I'm thinking about changing the color of `::` in my Julia Color Themes extension for VS Code. The reason I would like to do that is because the contrast between red and magenta is not very good, which you can see here:

![image](https://user-images.githubusercontent.com/8310743/106323552-35331780-623d-11eb-9e64-43bdc58a59d1.png)

In other words, I'd like to increase the contrast between `::` and `AbstractXML` in that screenshot. I think yellow or blue (which are already used in the color scheme) might be a good choice. However, the token for `::` is `keyword.operator.relation.julia`, so I can't change the color for `::` without changing the color for all relations.

Could we make the token for `::` more specific? Perhaps `keyword.operator.relation.type-assert.julia`?

**Comment by pfitzseb** [comment]
What do you think about #239?

**Comment by CameronBieganek** [comment]
Looks good! As far as I can tell, that will make `::`, `<:`, and `>:` all tokenize as `keyword.operator.relation.types.julia`. Is that correct?

**Comment by pfitzseb** [comment]
Yep.

**Comment by CameronBieganek** [comment]
Cool, looks good to me!
