### ISSUE TITLE
Elementwise operators not recognized

### ISSUE THREAD

**Issue by garborg** [JuliaEditorSupport/atom-language-julia#24]

**Comment by tpoisot** [comment]
They seem to be correctly recognized (I added specs to be sure)

**Comment by garborg** [comment]
I should have been more specific posting the issue. The problem is that there are element-wise operators that aren't recognized, not that no element-wise operators are recognized.

**Comment by tpoisot** [comment]
Do you have a list?

**Comment by garborg** [comment]
No list, but see `.+=`. I have a commit from an aborted PR that fixes other operator parsing issues as well as some of these, so I'll try to pull that out, add missing elementwise operators, and submit it separately soon.

**Comment by pfitzseb** [comment]
Seems fixed now.
