### ISSUE TITLE
Weird case of function tokenization when end of line comment includes parentheses

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaEditorSupport/atom-language-julia#240]
```julia
using StaticArrays

struct Point{Dim,T}
  coords::SVector{Dim,T}
end

Point((1,2)) # figures out that (Dim, T) = (2, Int)
Point((1,2)) # figures out that (Dim, T)
```

![image](https://user-images.githubusercontent.com/8310743/106943701-63a46d00-66eb-11eb-9428-a8927f13742e.png)

**Comment by pfitzseb** [comment]
The `=` is the issue here, not the closing parenthesis (because we think it's a short form function definition in that case...).
