### ISSUE TITLE
Unicode operators aren't highlighted

### ISSUE THREAD

**Issue by MarcMush** [JuliaEditorSupport/atom-language-julia#253]
operators that are not defined in Base Julia aren't highlighted, which makes code less readable when defining custom operators:

![vscode](https://user-images.githubusercontent.com/35898736/140775702-2b732967-21b3-4110-8cbe-dcd75433dbbb.PNG)

```julia
# github
a+b
a⊕b
a▷b
a*ᵉb
```

(here, it looks like `a⊕b`, `a▷b` and `ᵉb` are variables)

for reference, `OhMyREPL.jl` highlights them correctly:

![ohmyrepl](https://user-images.githubusercontent.com/35898736/140775952-920a7cf1-8b67-4397-857c-5518d07dd968.PNG)

**Comment by CameronBieganek** [comment]
Here's a few more examples:

<img width="179" alt="image" src="https://github.com/JuliaEditorSupport/atom-language-julia/assets/8310743/e268cb42-be7f-47b1-a667-69100b7f4b1e">

Those operators are listed as comparison operators in `julia-parser.scm`. It would be nice if we could tokenization for these various Unicode operators.

<img width="445" alt="image" src="https://github.com/JuliaEditorSupport/atom-language-julia/assets/8310743/d5bd50fc-3a41-480e-a272-c7d433a33124">
