### ISSUE TITLE
Additional keywords

### ISSUE THREAD

**Issue by TheWitheredStriker** [JuliaEditorSupport/atom-language-julia#257]
I found multiple Julia keywords that aren't highlighted:

`importall`, `typealias` and `type` at [jayschwa/Quake2.jl/blob/master/src/bsp/Mesh.jl](https://github.com/jayschwa/Quake2.jl/blob/master/src/bsp/Mesh.jl)

![image](https://user-images.githubusercontent.com/38614982/155141175-2c184869-32cc-4e27-bbbe-1fd284d6dcf8.png)
![image](https://user-images.githubusercontent.com/38614982/155141774-4a82634f-e4ca-42e6-8dec-730cdd8e53f1.png)

`immutable` at [jayschwa/Quake2.jl/blob/master/src/bsp/File.jl](https://github.com/jayschwa/Quake2.jl/blob/841292d9db32e37a22ff0579b8a42abdc5fed73c/src/bsp/File.jl)

![image](https://user-images.githubusercontent.com/38614982/155142032-138a936f-2151-47fe-aed9-71237018bab4.png)

`importall`, `immutable` and `typealias` are not in the grammar file from what I can tell (I would suggest their addition). `type` is, leaving me confused as to why it is not highlighted correctly.

**Comment by pfitzseb** [comment]
None of these are keywords in recent versions of Julia.
