### ISSUE TITLE
Future development after Atom's sunset

### ISSUE THREAD

**Issue by mitiemann** [JuliaEditorSupport/atom-language-julia#273]
While one could still technically install `atom`, it [has been archived](https://github.blog/2022-06-08-sunsetting-atom/) and development has stopped in favor of VSCode. To me, this begs how the future development of the grammar should be organized.

In particular, the contribution guide is written with development in Atom in mind. However, the more time has passed since Atom's sunset, the less likely it will be that someone will install an old, unmaintained editor only to extend the grammar. To me, this would imply that a sustainable solution would include a setup that has VSCode as its primary development environment.

I could help updating the README, etc., but I'm not familiar enough with the VSCode extension ecosystem or the Github Actions in place such that I could update these myself. I can, however, act as a guinea pig to test a novel description.

**Comment by pfitzseb** [comment]
Yeah, that's very reasonable :) I'll take a stab at updating the readme and ping you on the PR that does that.
