### ISSUE TITLE
Docstring Highlighting

### ISSUE THREAD

**Issue by MikeInnes** [JuliaEditorSupport/atom-language-julia#33]
This docstring makes highlighting go funky:

```
"""
    @switch isa(x, _) begin
      Integer; "x is an integer!"
      FloatingPoint; "x is a float!"
      "x is something else!"
    end

Where `_` is replaced by the value for testing in each case. The final
"""
macro switch(args...)
```

![screenshot 2015-08-02 12 51 32](https://cloud.githubusercontent.com/assets/2234614/9025992/403015fe-3915-11e5-8da9-9b8745a64c8d.png)

The `_` seems to start an italic section despite being in a code block, and this doesn't happen without the `)`. Also, for some reason the final `"""` isn't closing off the docstring either.

Highlighting top-level strings as markdown is a great idea, but maybe it would then be good to remove the string scope so that the default colour isn't yellow. It'd also be pretty cool if we could highlight indent code blocks as Julia by default.

**Comment by garborg** [comment]
These fixes would be great.

Re: improving highlighting generally, I have a PR with comprehensive improvements that I'm pretty excited about, but they're languishing locally until a parsing bug is fixed upstream: atom/first-mate#52. I don't know if anyone has done any work on first-mate -- hopefully it's fixed soon.

**Comment by spencerlyon2** [comment]
@garborg, really looking forward to your improvements. I think a solid cleanup would be great. Most of what is there right is just inherited from the [textmate bundle](https://github.com/JuliaLang/Julia.tmbundle). We've made a few changes, but not a general overhaul like I think you are working on.

**Comment by spencerlyon2** [comment]
@one-more-minute I think you can just put a space between the `_` and `)` to fix the italic issue. I just tested and it looks like that would fix the docstring not ending issue also.

This also seems like more of a problem in the [atom-gfm](https://github.com/atom/language-gfm) grammar since it only happens when we `include` their grammar

**Comment by spencerlyon2** [comment]
@garborg any update on this? I see that very little has happened over at atom/first-mate, but are some of your improvements independent of that?

**Comment by spencerlyon2** [comment]
Oh and @one-more-minute, I currently have this in my styles.less

```
 atom-text-editor::shadow {
   .string.docstring.julia {
     color: @syntax-result-marker-color;
   }
 }
```

It makes it more or less the same color as comments, depending on how the syntax uses that variable. It would  be better to somehow pop the string scope when we enter a docstring though

**Comment by garborg** [comment]
The issue in atom/first-mate has been switched from 'bug' to 'matches macromates', which I imagine means won't fix. So dead end there until Atom supports more powerful tokenizers -- there links in atom/first-mate#52 to issues suggesting supporting external tokenizers and/or Sublime3's grammar.

Unfortunately my plan to highlight almost everything correctly falls apart with a grammar that ignores 'end' patterns, so much of what I did will be useless. I do have plenty of new tests that should pass, but it'll, but it'll take a bit or work to try to salvage actual changes.

**Comment by spencerlyon2** [comment]
Darn, that's disappointing. 

I was looking forward to sane/complete scoping for everything.

**Comment by tpoisot** [comment]
The markdown specification used by `language-gfm` is that an italic string is started by an italic delimiter (`_` or `*`) followed by anything that is not a space. 

The following code works well:

    """
    @switch `isa(x, _)` begin
      Integer; "x is an integer!"
      FloatingPoint; "x is a float!"
      "x is something else!"
    end
    Where `_` is replaced by the value for testing in each case. The final
    """
    macro switch(args...)

**Comment by pfitzseb** [comment]
This is the same as https://github.com/atom/language-gfm/issues/44, btw.

**Comment by pfitzseb** [comment]
Fixed on master.
