### ISSUE TITLE
Identifier highlighting

### ISSUE THREAD

**Issue by MikeInnes** [JuliaEditorSupport/atom-language-julia#34]
Regular variables like `foo` are not highlighted any more specifically than `source.julia`. I don't know what the standard is for variables but if we could label them as `identifier` or `variable` or something that would be really useful.

The reason being that secret plugins, which may or may not exist, might want to highlight variables differently depending on whether they are defined or not.

**Comment by spencerlyon2** [comment]
[Secret plugins](https://github.com/JunoLab) -- looking forward to it!

I suppose we could do this. Wouldn't the  regex for a valid Julia variable name be the same as the regex for a value function name? I guess there are some symbols that are allowed to be function names, but now variable names (I'm thinking unicode operators like `\dot[TAB]` and `\in[TAB]`).

**Comment by one-more-minute** [comment]
Matching against identifiers starting with unicode word characters, and containing only those, number characters and `!`, seems to work well. Could also check the source of `Base.isidentifier` in case that's not exact.

**Comment by spencerlyon2** [comment]
For reference:

```julia
is_id_start_char(c::Char) = ccall(:jl_id_start_char, Cint, (UInt32,), c) != 0
is_id_char(c::Char) = ccall(:jl_id_char, Cint, (UInt32,), c) != 0
function isidentifier(s::AbstractString)
    i = start(s)
    done(s, i) && return false
    (c, i) = next(s, i)
    is_id_start_char(c) || return false
    while !done(s, i)
        (c, i) = next(s, i)
        is_id_char(c) || return false
    end
    return true
end
isidentifier(s::Symbol) = isidentifier(string(s)
```

and the `ccall` functions (in src/flisp/julia_extensions.c):

```C
DLLEXPORT int jl_id_start_char(uint32_t wc)
{
    if ((wc >= 'A' && wc <= 'Z') || (wc >= 'a' && wc <= 'z') || wc == '_')
        return 1;
    if (wc < 0xA1 || wc > 0x10ffff)
        return 0;
    const utf8proc_property_t *prop = utf8proc_get_property(wc);
    return is_wc_cat_id_start(wc, prop->category);
}

DLLEXPORT int jl_id_char(uint32_t wc)
{
    if ((wc >= 'A' && wc <= 'Z') || (wc >= 'a' && wc <= 'z') || wc == '_' ||
        (wc >= '0' && wc <= '9') || wc == '!')
        return 1;
    if (wc < 0xA1 || wc > 0x10ffff)
        return 0;
    const utf8proc_property_t *prop = utf8proc_get_property(wc);
    utf8proc_propval_t cat = prop->category;
    if (is_wc_cat_id_start(wc, cat)) return 1;
    if (cat == UTF8PROC_CATEGORY_MN || cat == UTF8PROC_CATEGORY_MC ||
        cat == UTF8PROC_CATEGORY_ND || cat == UTF8PROC_CATEGORY_PC ||
        cat == UTF8PROC_CATEGORY_SK || cat == UTF8PROC_CATEGORY_ME ||
        cat == UTF8PROC_CATEGORY_NO ||
        // primes (single, double, triple, their reverses, and quadruple)
        (wc >= 0x2032 && wc <= 0x2037) || (wc == 0x2057) ||
        // Other_ID_Continue
        wc == 0x0387 || wc == 0x19da || (wc >= 0x1369 && wc <= 0x1371))
        return 1;
    return 0;
}
```
