### ISSUE TITLE
Autoindent of macro'd begin blocks

### ISSUE THREAD

**Issue by MikeInnes** [JuliaEditorSupport/atom-language-julia#37]
Only a small thing, but this doesn't auto-indent the cursor on newline:

``` julia
@time foo begin
```

**Comment by spencerlyon2** [comment]
Odd because [this line](https://github.com/JuliaLang/atom-language-julia/blob/master/settings/language-julia.cson#L6) suggests that it should. Maybe a bug on the atom side?

**Comment by mbauman** [comment]
No, it doesn't allow anything extra between the macro and the `begin`.  Really, I think that could be extended to any line that ends with `begin\s*`.  (Same goes for the tmbundle).

**Comment by spencerlyon2** [comment]
Yeah I totally agree with the `begin\s*` idea

**Comment by ssfrr** [comment]
This seems to have regressed between 0.7.0 and 0.8.0.

**Comment by pfitzseb** [comment]
Hm, I don't see any regression for the `@time foo begin` case.

**Comment by ssfrr** [comment]
Oh, my test case is slightly different:

```
@testset "testing some stuff" begin
"not-indented"
end
```

This indented properly with 0.7.0 but not 0.8.0.

**Comment by pfitzseb** [comment]
Right. That one's pretty hard to solve as far as I can tell though, because I'm not sure how to differentiate between 
`@macro "foo bar begin"` and `@macro "foo bar" begin` (or even `@macro "foo \"bar\" begin" begin`). I thought this could be solved by using a negative lookahead inside of a negative lookbehind, but first-mate (or whatever the regex engine is called) doesn't support that...

**Comment by ssfrr** [comment]
FWIW I think that a false positive on `@macro "foo bar begin"` is preferable to a false negative on `@macro "foo bar" begin` (which is common with `@testset`). I was so happy when the latter started working, and then my joy was dashed with the 0.8.0 update.

**Comment by pfitzseb** [comment]
Alright, something like 
```
increaseIndentPattern: "(^(\\s*|.*=\\s*|.*@\\w*\\s*)[\\w\\s]*(if|while|for|function|macro|immutable|type|let|quote|try|begin|.*\\)\\s*do|else|elseif|catch|finally)\\b(?!.*\\bend\\b[^\\]]*$).*$|(begin|do|try|let|quote)\\b(?!\\s*\\bend\\b[^\\]]*$)\\s*$)"
```
is a bit better, but also a bit of a monstrosity (gut feeling: it's impossible to get this right for *all* cases with a single regex). It will fail for
```julia
@foo "bar begin
    " # this is indented
a = a == a ? 1 : try a catch e
# not indented
end
```
but work for the cases above. I'll think about this a bit more tomorrow, but if someone either wants to propose any ideas or wants to try the regex pattern above, please do!
