### ISSUE TITLE
Ligature support is being removed in some cases.

### ISSUE THREAD

**Issue by Libbum** [JuliaEditorSupport/atom-language-julia#49]
Atom v1.1.0 now officially supports ligatures. When this package is active, not all ligatures are displaying. 

An example: The left frame has a Julia file and the right an untitled document. The untitled document has `!=` and `<=` ligatures working, although once saved into a .lj and syntax highlighted, the ligatures are no longer visible.
![julia](https://cloud.githubusercontent.com/assets/3059508/10849671/1200f146-7f22-11e5-90a6-0bb948e3d5ed.png)

Not all ligatures are removed, for example `->` still works. The problem doesn't occur in other file types (for example a .cpp or .hs file, which aren't syntax highlighted via this package), and I've tested this with most of the ligature enabled fonts: no changes there either.

**Comment by spencerlyon2** [comment]
This is very strange. 

I don't expect our syntax highlighting to change anything. We are just supplying the highlighting engine with a set of regular expressions that tell Atom how to highlight each character -- not how they should be displayed.

Sorry I don't have anything more constructive to say here... I'm just puzzled

**Comment by Libbum** [comment]
I totally agree! 

It may actually be something else and not the syntax highlighter at all. But I don't know enough about how the ligature support works under the hood. If anyone can suggest some more troubleshooting steps for me to investigate to try and rule out any involvement of this package that'd be great!

**Comment by spencerlyon2** [comment]
So it seems to work for me in a julia file or other

![screen shot 2015-10-30 at 11 57 42 am](https://cloud.githubusercontent.com/assets/1001948/10850702/746d2ae0-7efd-11e5-8a7e-25d15161342c.png)

**Comment by Libbum** [comment]
OK cool. I'm going to disable everything and turn on packages one at a time.

**Comment by 50Wliu** [comment]
This happens if the tokenization changes between the characters; eg if the `!` and `=` have different tokens associated to them.  You might want to check if that's happening.

**Comment by Libbum** [comment]
@50Wliu, thanks for the tip. Since it seems I'm the only one with this issue, can you give me a bit more detail on how I'd check this? I'm quite new to atom development. 

The only new thing I can add is that I've checked the scopes applied at the cursor position between a ligature. If I denote the cursor position with |, then checking (for example) <|= gives me `source.julia, keyword.operator.update.julia` with a julia file, and similar keyword.operator.* scopes for other languages such as haskell and chapel. The only visual differences of the latter two is they actually give me ligatures.

**Comment by 50Wliu** [comment]
What about the scope of `<`?  Is it exactly the same as `=`?

**Comment by Libbum** [comment]
Ahh, no they aren't. `<` is `keyword.operator.relation.julia` and `=` is `keyword.operator.update.julia`. Can someone who isn't getting this error check to see their scopes for these two?

**Comment by 50Wliu** [comment]
Ok.  Here's the problem: https://github.com/JuliaLang/atom-language-julia/blob/master/grammars/julia.cson#L239
`<=` and `>=` have to be matched before `<` and `>`, respectively.

**Comment by Libbum** [comment]
Excellent! That fixed `<=` and `=>`. I'll take a look at some more fixes (for example `!=`) of similar nature and create a pull request.

**Comment by jianghaizhu** [comment]
I still have the ligature rendering problem. I am using Atom 1.9.2, font "Hasklig". Only a few ligatures, like "->", are working. And most of them don't.

**Comment by cdsousa** [comment]
I still miss ligatures on `!==`, `===`, `++`, `--`, and possible others. I tried to solve it but unsuccessfully...

**Comment by jianghaizhu** [comment]
@Libbum It seems like many people, including me,  still have problems with ligature. Is it working for you? 

@spencerlyon2 maybe this issue can be reopened?

**Comment by Libbum** [comment]
I haven't been using Julia for a while, so can't say for sure. It's my birthday weekend so I'm out,  but will take a look soon at the issues presented above.

**Comment by jianghaizhu** [comment]
@Libbum No hurry. Happy birthday!

**Comment by pfitzseb** [comment]
Which ligatures aren't working for you?

**Comment by jianghaizhu** [comment]
as mentioned above by @cdsousa

**Comment by Libbum** [comment]
A few questions: 

1. Is anyone having troubles with ligatures other than `!==`, `===`, `++` or `--`? 
2. Are all of you using Hasklig?


I'm using PragmataPro, (but I'm also now checking against Hasklig). I see a few issues for us here, considering that ligature support on both fonts do not cover the complete Julia scope.

For example, afaik, Hasklig has not implemented `--` or `>=` for that matter. (see [currently implemented ligatures](https://github.com/i-tu/Hasklig/blob/master/README.md))
I have PragmataPro working with `--` though, but that font is yet to implement `==` or `===`.

I have a working patch for the four mentioned ligatures above, that should automatically work if coverage in the fonts are updated in a future version, but until then we can't do much more. If anyone has any more ligatures they think we've missed, let me know and I'll take a look. Otherwise I can send this PR through and we can close the issue again for now.

**Comment by spencerlyon2** [comment]
Thanks for checking in this @Libbum. I'd be happy to accept a PR that preps us for whenever fonts implement the ligatures we might find in valid Julia code.

**Comment by Libbum** [comment]
Alright. Give me a bit of time to check that I have full coverage of that. I'll validate against the Operator Precedence section of the [manual](http://docs.julialang.org/en/release-0.5/manual/mathematical-operations/).

**Comment by spencerlyon2** [comment]
Excellent, thanks again.

Also -- no rush (github missed the -- ligature 😏 )

**Comment by jianghaizhu** [comment]
Yes. Lacking of `>=` and `<=` in Hasklig is really inconvenient. That is why I am switching to` Fira Code`, which I consider has the most ligatures implemented. By the way, is there a list of all Julia operators that we can use to test the ligatures?

**Comment by Libbum** [comment]
Have any of you came across problems with my changes? If everyone is happy with the improvements Spencer and I are ready to merge this soon.
