### ISSUE TITLE
Dot-transpose not highlighted correctly

### ISSUE THREAD

**Issue by Keno** [JuliaEditorSupport/atom-language-julia#57]
<img width="485" alt="screen shot 2016-01-18 at 2 27 53 pm" src="https://cloud.githubusercontent.com/assets/1291671/12392480/b0098176-bdef-11e5-90b6-ebbabf7a36af.png">

**Comment by spencerlyon2** [comment]
From [here](https://github.com/JuliaLang/atom-language-julia/blob/master/grammars/julia.cson#L273-L274) it looks like this should be taken care of.

I don't have time to dig in myself right now, but eventually I will

**Comment by pfitzseb** [comment]
Good thing that `the ".'" operator is discontinued` then :)
