### ISSUE TITLE
Auto indentation of function calls

### ISSUE THREAD

**Issue by MikeInnes** [JuliaEditorSupport/atom-language-julia#71]
ref https://github.com/JunoLab/uber-juno/issues/7

**Comment by spencerlyon2** [comment]
Hmm off the top of my head I'm not sure what the issue is here. 

Any ideas?

**Comment by pfitzseb** [comment]
I haven't yet seen any grammar do this -- the only thing is to indent the next line by a bit if there's an open paren:
```julia
longfoo(arg1, 
  arg2,
  arg3)
```
But if you manually indent the second line up to the paren (or wherever, really), the line after that will keep that indent:
```julia
longfoo(arg1,
        arg2,
#       | you'll get here on enter
```

I don't know much about the capabilities of grammars in Atom, but I'd think that something like that should be done by a code beautifier or something similar...

**Comment by spencerlyon2** [comment]
Smart(er) indentation for atom in general would be great. syntax aware indentation is always one thing that makes it feel nice when I open up emacs for a bit

**Comment by pfitzseb** [comment]
Somewhat related: https://github.com/atom/atom/pull/10384

So when that parsing system rework lands we should be able to do what is proposed here.

**Comment by vancleve** [comment]
Can this be adapted to help since it produces PEP8 indenting for Python?

[](https://github.com/DSpeckhals/python-indent)

**Comment by pfitzseb** [comment]
Yeah, definitely, but that's kind of out of scope for this package.
