### ISSUE TITLE
"\\" highlighting

### ISSUE THREAD

**Issue by gdkrmr** [JuliaEditorSupport/atom-language-julia#72]
See screenshot:
![screenshot_2016-07-12_09-47-20](https://cloud.githubusercontent.com/assets/12512930/16759209/1432ff78-4816-11e6-8a08-d0d470ceece4.png)

**Comment by spencerlyon2** [comment]
Thanks for reporting.

I don't have a ton of extra bandwidth at the moment to look into this. If anyone else has a few minutes to check it out that'd be helpful
