### ISSUE TITLE
`continue!` is mis-highlighted

### ISSUE THREAD

**Issue by Keno** [JuliaEditorSupport/atom-language-julia#74]
`continue!` is a valid identifier

![screen shot 2016-07-21 at 9 26 31 pm](https://cloud.githubusercontent.com/assets/1291671/17043995/d5bd2cde-4f89-11e6-84c5-b1e918d23dc0.png)

**Comment by ararslan** [comment]
This appears to have been fixed?

![screen shot 2016-09-30 at 9 12 13 pm](https://cloud.githubusercontent.com/assets/6396159/19011675/a1211fd4-8752-11e6-8ee3-f163ef149086.png)

**Comment by pfitzseb** [comment]
Only if you have parens after `continue!`, which totally seems sane to me.
