### ISSUE TITLE
Semi-OT: Linter support in atom for Julia?

### ISSUE THREAD

**Issue by sbromberger** [JuliaEditorSupport/atom-language-julia#8]
Hi all,

Sorry - didn't know where else to put this, but it would be great to have something that integrates with [atom-linter](https://github.com/AtomLinter/Linter).

**Comment by johnmyleswhite** [comment]
Definitely doable. We just need to make Lint.jl output the official linter output format.

**Comment by spencerlyon2** [comment]
Ha, no problem. I was doing some research this morning and was going to sketch out an implementation later today.

**Comment by sbromberger** [comment]
Rockin'. Thanks - I wish I had the skills to contribute beyond testing :)

**Comment by johnmyleswhite** [comment]
I think they're pretty easy to develop. The docs at https://atom.io/docs/v0.192.0/hacking-atom-tools-of-the-trade are very readable.

**Comment by spencerlyon2** [comment]
current link: https://atom.io/docs/v1.0.0/hacking-atom-tools-of-the-trade

And yeah, I know next to nothing about web tools, but it has been surprisingly easy.

@johnmyleswhite, interested in hacking this up later? Maybe while we are all here we can ask @tonyhffong how we might hook up the `linter-server` to get decent performance for all lints after the first.

**Comment by johnmyleswhite** [comment]
Yeah, I'd be up for working on this.

**Comment by sbromberger** [comment]
I'm happy to lend a hand testing whenever you've got a prototype ready.

**Comment by spencerlyon2** [comment]
Tried it for a while... no luck

I got atom-linter to run a script that was calling out to a `lintserver` from Lint.jl. I saw in the terminal running `lintserver` that it was indeed  printing the lint errors, but it didn't seem like the string containing the error messages was ever successfully given to atom...

**Comment by johnmyleswhite** [comment]
I'll work on this tomorrow morning and see what I can do.

**Comment by spencerlyon2** [comment]
@johnmyleswhite, any luck with this?

I thought more about it and I think do something like this to `spawn` a new julia instance and retain it for future listing:

```coffeescript

**Comment by johnmyleswhite** [comment]
Sorry, didn't have a chance to write any code yesterday. I'll see if I can dig in a bit tonight.

**Comment by spencerlyon2** [comment]
No problem. I think that if we get this `spawn` thing right we will be able to do some cool stuff (`macroexpand` tooltips that you brought up...)

**Comment by johnmyleswhite** [comment]
Started working on this. I think I need to maintain an Atom installation to get this right since Nuclide is a little weird.

**Comment by spencerlyon2** [comment]
Hmm. Is that a problem? I suspect you will be using Nuclide as your main editor

**Comment by johnmyleswhite** [comment]
We'll find out. I have a personal laptop that I can install Atom 1.0 on, so I can work on things like this while I sort everything out.

**Comment by spencerlyon2** [comment]
I think we should probably close this ans defer this type of functionality to the Julia client package. 

@one-more-minute what do you think about that?

**Comment by one-more-minute** [comment]
Linter support should definitely be separate from basic editor support, yeah. If it's going through Lint.jl statically it could be its own package entirely.

**Comment by TeroFrondelius** [comment]
I am very interested about this. Did any of you work on this matter further? If there is a separate package can you point me the way? Also if there is not, any old half working code would be appreciated because I tried to look the examples of other languages, but it seemed so overwhelming.

**Comment by pfitzseb** [comment]
As far as I know no one did any work on an Lint.jl Atom plugin, but the [vscode-plugin](https://github.com/JuliaEditorSupport/julia-vscode) does have Lint.jl support afaik.

**Comment by TeroFrondelius** [comment]
Almost there, I have a some very basic mistake in coffeescript. Any extra eyes would be appreciated. https://github.com/TeroFrondelius/linter-julia/issues/1

**Comment by TeroFrondelius** [comment]
Here is the unpublished version, if someone wants to be a test pilot:
https://github.com/TeroFrondelius/linter-julia

Please feel free to open issues for discussion, feature requests, test piloting etc.

**Comment by HarrisonGrodin** [comment]
@TeroFrondelius This is fantastic! Only suggestion would be getting the server to internally launch. :smile:
