### ISSUE TITLE
Dot-broadcasts aren't colored like function calls

### ISSUE THREAD

**Issue by ararslan** [JuliaEditorSupport/atom-language-julia#81]
It appears `exp.(x)` isn't highlighted at all, whereas the `exp` is highlighted in `exp(x)`.

![screen shot 2016-09-30 at 9 03 04 pm](https://cloud.githubusercontent.com/assets/6396159/19011630/519f6610-8751-11e6-9dfa-f71ee0249a17.png)

**Comment by spencerlyon2** [comment]
I _think_ this issue can be fixed by adding a `\.?` to just before the last `\(` on [this line](https://github.com/JuliaEditorSupport/atom-language-julia/blob/871efe50aac953def26ff4a20747c7956bb6a798/grammars/julia.cson#L106)
