### ISSUE TITLE
Doesn't handle this syntax `t("(")`

### ISSUE THREAD

**Issue by jkroso** [JuliaEditorSupport/atom-language-julia#92]
Everything after is ends up being highlighted as if it was a string. So in that example the closing brace would be highlighted the same colour as the brace between the quotes.

```julia
t("(")
```

This seems to of been caused by the latest update too by the way

**Comment by spencerlyon2** [comment]
Hmm, I can't reproduce:

![screen shot 2016-10-28 at 2 52 50 pm](https://cloud.githubusercontent.com/assets/1001948/19818555/3d160f90-9d1e-11e6-8e22-b4c702244e55.png)

**Comment by jkroso** [comment]
I'm running Atom@v1.11.2 and language-julia@v0.9.11. Are you the same?

**Comment by spencerlyon2** [comment]
Oh, I think this must be the issue from #93 .

I just pushed v0.10.0 of this package, will you try updating to see what happens?

**Comment by jkroso** [comment]
Yup that fixs it. Thanks
