### ISSUE TITLE
package name and version

### ISSUE THREAD

**Issue by jstrube** [JuliaEditorSupport/atom-language-julia#93]
since the release of 0.9.0, atom seems to be extremely confused about which package to install, this one, or the one created by tpoisot.

Could you please tag 0.9.1, just so atom can distinguish the two packages again.

**Comment by spencerlyon2** [comment]
What is especially troubling (to atom) about version number 0.9.0?

**Comment by jstrube** [comment]
The symptom is that every time I try to install this package, I end up with the one from tpoisot, which is horribly outdated and has an annoying syntax highlighting bug.
Are you asking me why atom cannot distinguish two packages with the same name and same version number?
I have no idea.
Thanks for bumping the version.

**Comment by spencerlyon2** [comment]
sorry I didn't understand that 0.9.0 happened to be what the tpoisot package was at before this one started.

Glad it worked out
