### ISSUE TITLE
Markup broken for certain Blockquotes in @doc s

### ISSUE THREAD

**Issue by kellertuer** [JuliaEditorSupport/atom-language-julia#97]
If I have the following @doc string
```
"""
    myFunction() computes something based on the reference
> My Paper I Would like to quote
> Further quote...
"""
```
The editor gets confused in its markup and does not recognize the closing """. Everything until the end of the document is marked as if it was code in (colorwise).

However as noted by @spencerlyon2 [here](https://github.com/JunoLab/uber-juno/issues/23) adding an empty line direktly after the last line starting with `>` fixes the markup, i.e.
```
"""
    myFunction() computes something based on the reference
> My Paper I Would like to quote
> Further quote...

"""
```
yields a correct color markup and the same if even theres more text following the quote, it only colors the code following correctly if theres a blank line after the blockquote.

**Comment by kalmarek** [comment]
any fix for that?

**Comment by pfitzseb** [comment]
This is fixed on master (and therefore with the next release).
