### ISSUE TITLE
Colouring of typed functions different

### ISSUE THREAD

**Issue by kellertuer** [JuliaEditorSupport/atom-language-julia#98]
I noticed that usually functions (kind a orange) that are typed get the type brace colored yellowish,
which I think is nice. However, this does not happen for typed operators, as the following screenshot illustrates.
![typedcolor](https://cloud.githubusercontent.com/assets/115566/20719052/06677816-b65b-11e6-87a7-8f3c0a4007b1.png)
Is that intentional? I think it would be nicer to have a typed operator also embraced with a yellowish type bracket

**Comment by spencerlyon2** [comment]
What syntax highlighting theme are you using here?

One mother difference between these two lines of code is the use of the `function` keyword when defining `add`.

What happens to the braces when you do

```julia
function +{T <: B}(a::T, b::T)
end
```
?

**Comment by pfitzseb** [comment]
This shouldn't be an issue anymore (feel free to reopen if I'm wrong).
